repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy

  - repo: local
    hooks:
      - id: mix-format-database
        name: mix format (database)
        description: Formats Elixir files with mix format.
        language: system
        entry: cd database && mix format
        files: \.exs?$

      - id: mix-format-protobuf-elixir
        name: mix format (protobuf-elixir)
        description: Formats Elixir files with mix format.
        language: system
        entry: cd protobuf-elixir && mix format
        files: \.exs?$

      - id: compile-protos-python
        name: Compile Protobufs (Python)
        description: This hook compiles protobufs for Python.
        entry: python protobuf-python/build.py
        language: python
        files: \.proto$
        pass_filenames: false

      - id: compile-protos-elixir
        name: Compile Protobufs (Elixir)
        description: This hook compiles protobufs for Elixir.
        entry: protoc --elixir_out=plugins=grpc:./protobuf-elixir/lib/ --proto_path=./protobuf
        language: system
        files: \.proto$
